-- Store embeddings as halfvec, and stop writing the dimension down.
--
-- Two changes that only look separate.
--
-- STORAGE.  fp16 halves both heap and index for negligible recall cost, and it
-- is the prerequisite for the binary-plus-rescore stage: HNSW indexes `vector`
-- to 2,000 dimensions but `halfvec` to 4,000 (ADR 0001, D7).  At the 4.2M
-- vectors D7 sizes, that is 16.7 GB of index against 8.7 GB, and RAM is the
-- ceiling.  Doing it now costs one table rewrite of a pre-production schema;
-- doing it later costs a rewrite of every tenant's vectors.
--
-- DIMENSION.  `vector(1024)` was written down in four places — two column
-- declarations, the q_embedding parameter of every function that takes a query
-- vector, and the RETURNS TABLE clause of pgkg_search() — while
-- config.embed_dim, the one place that looks authoritative, was read by
-- nothing.  Changing embedder meant editing SQL in step with Python and hoping.
--
-- The dimension now has exactly one declaration: the column.
--
-- Postgres cannot parameterise a type modifier in plain SQL, so the DDL is
-- generated by a plpgsql helper.  The helper reads the dimension from the
-- column it is converting, which is why this migration contains no dimension
-- literal at all: whatever 002 declared is carried forward untouched, and from
-- here on the catalog is the only statement of it.  pgkg_embedding_dim() makes
-- that readable by later migrations and backfills instead of re-derived.
--
-- The function signatures take an UNMODIFIED halfvec instead.  This is not a
-- shortcut: Postgres DISCARDS type modifiers on function parameters and result
-- columns, so `vector(1024)` in a signature never constrained anything.  It was
-- documentation, and after this migration it would be false documentation.  The
-- dimension is enforced where it can be — by the column on write, and by the
-- distance operator, which rejects operands of different width on read.
--
-- A settings or registry table was the other option and is deliberately not
-- built here: ADR 0001 D8 puts `embedder_generations` in phase 1, and a phase-0
-- stand-in would have to be migrated away to make room for it.
--
-- D8 then needs no rewrite.  A second generation at another width is one call:
--     SELECT pgkg_set_embedding_storage('emb_prop_g2', 'vec',
--                                       'emb_prop_g2_vec_idx', 768);
-- and no function signature changes, because none of them names a width.
--
-- The wire type stays fp32.  pgkg_search() still returns `vector`, because
-- widening fp16 is exact and every client codec — and the Python-side MMR that
-- consumes the column — already handles it.  Teaching clients halfvec is a
-- separate decision with no storage consequence.
--
-- DROP-then-CREATE of the three functions is forced, not stylistic.  A
-- parameter type is part of a function's identity, so CREATE OR REPLACE would
-- leave the fp32 overload in place beside the new one and make every existing
-- call that passes a NULL or untyped embedding ambiguous.  The bodies are
-- carried over unchanged; no retrieval stage is duplicated, because each still
-- lives in its own function from 010.


-- 1. The declared width of an embedding column.  pgvector stores the dimension
-- directly in atttypmod; an unconstrained column has -1 and reads as NULL.
CREATE FUNCTION pgkg_embedding_dim(p_table TEXT, p_column TEXT)
RETURNS INT
LANGUAGE SQL
STABLE
AS $$
    SELECT NULLIF(a.atttypmod, -1)
    FROM pg_attribute a
    WHERE a.attrelid = p_table::regclass
      AND a.attname = p_column
      AND NOT a.attisdropped;
$$;


-- 2. Put an embedding column on halfvec storage with a cosine HNSW index.
-- p_dim defaults to the width the column already declares, so a conversion
-- never restates it.  p_index NULL leaves the column unindexed.
--
-- The index is dropped first rather than left to the implicit rebuild: an
-- ALTER through a vector_cosine_ops index fails outright, because that operator
-- class does not accept halfvec.
CREATE FUNCTION pgkg_set_embedding_storage(
    p_table  TEXT,
    p_column TEXT,
    p_index  TEXT,
    p_dim    INT DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_dim INT := COALESCE(p_dim, pgkg_embedding_dim(p_table, p_column));
BEGIN
    IF v_dim IS NULL THEN
        RAISE EXCEPTION
            'no dimension declared on %.% and none supplied',
            p_table, p_column;
    END IF;

    IF p_index IS NOT NULL THEN
        EXECUTE format('DROP INDEX IF EXISTS %I', p_index);
    END IF;

    EXECUTE format(
        'ALTER TABLE %s ALTER COLUMN %I TYPE halfvec(%s) USING %I::halfvec(%s)',
        p_table::regclass, p_column, v_dim, p_column, v_dim
    );

    IF p_index IS NOT NULL THEN
        EXECUTE format(
            'CREATE INDEX %I ON %s USING hnsw (%I halfvec_cosine_ops)',
            p_index, p_table::regclass, p_column
        );
    END IF;
END;
$$;


-- 3. Convert the two embedding columns, carrying their declared width forward.
SELECT pgkg_set_embedding_storage('propositions', 'embedding', 'prop_emb_idx');
SELECT pgkg_set_embedding_storage('entities', 'embedding', 'entities_embedding_idx');


-- 4. Vector retrieval, on an unmodified halfvec query parameter.  A caller
-- binding fp32 is unaffected: vector -> halfvec is an implicit cast, so the
-- existing '[...]'::vector call sites resolve to this function unchanged.
DROP FUNCTION IF EXISTS pgkg_vector_candidates(vector, TEXT, TEXT, INT);

CREATE FUNCTION pgkg_vector_candidates(
    q_embedding  halfvec,
    p_namespace  TEXT DEFAULT 'default',
    p_session_id TEXT DEFAULT NULL,
    k_initial    INT  DEFAULT 200
) RETURNS TABLE (
    item_id   UUID,
    kind      TEXT,
    rank      INT,
    raw_score REAL
)
LANGUAGE SQL STABLE
AS $$
SELECT
    p.id,
    'vec'::TEXT,
    (ROW_NUMBER() OVER (ORDER BY p.embedding <=> q_embedding))::INT,
    (1.0 - (p.embedding <=> q_embedding))::REAL
FROM propositions p
WHERE q_embedding IS NOT NULL
  AND p.embedding IS NOT NULL
  AND p.namespace = p_namespace
  AND p.superseded_by IS NULL
  AND (
        p_session_id IS NULL
        OR p.session_id = p_session_id
        OR p.session_id IS NULL
      )
ORDER BY p.embedding <=> q_embedding
LIMIT k_initial;
$$;


-- 5. Entity resolution, likewise.
DROP FUNCTION IF EXISTS pgkg_link_entity(TEXT, TEXT, TEXT, vector, REAL);

CREATE FUNCTION pgkg_link_entity(
    p_namespace  TEXT,
    p_name       TEXT,
    p_type       TEXT,
    p_embedding  halfvec,
    p_threshold  REAL DEFAULT 0.85
) RETURNS UUID
LANGUAGE plpgsql
SECURITY INVOKER
AS $$
DECLARE
    v_id UUID;
BEGIN
    -- 1. Exact name + type match within namespace
    SELECT id INTO v_id
    FROM entities
    WHERE namespace = p_namespace
      AND name = p_name
      AND (type = p_type OR (type IS NULL AND p_type IS NULL))
    LIMIT 1;

    IF v_id IS NOT NULL THEN
        RETURN v_id;
    END IF;

    -- 2. Trigram + embedding similarity match
    IF p_embedding IS NOT NULL THEN
        SELECT id INTO v_id
        FROM entities
        WHERE namespace = p_namespace
          AND similarity(name, p_name) > 0.6
          AND (1 - (embedding <=> p_embedding)) > p_threshold
        ORDER BY (embedding <=> p_embedding)
        LIMIT 1;
    END IF;

    IF v_id IS NOT NULL THEN
        RETURN v_id;
    END IF;

    -- 3. Create new entity
    INSERT INTO entities (name, type, embedding, namespace)
    VALUES (p_name, p_type, p_embedding, p_namespace)
    RETURNING id INTO v_id;

    RETURN v_id;
END;
$$;


-- 6. pgkg_search(), unchanged except for the two types that named a width.
-- Composition, column list, scores and ordering are exactly as 010 left them.
DROP FUNCTION IF EXISTS pgkg_search(TEXT, vector, INT, INT, TEXT, TEXT, REAL, BOOLEAN, INT);

CREATE FUNCTION pgkg_search(
    q_text               TEXT,
    q_embedding          halfvec,
    k_retrieve           INT DEFAULT 100,
    k_initial            INT DEFAULT 200,
    p_namespace          TEXT DEFAULT 'default',
    p_session_id         TEXT DEFAULT NULL,
    recency_half_life_days REAL DEFAULT 30.0,
    expand_graph         BOOLEAN DEFAULT TRUE,
    rrf_k                INT DEFAULT 60
) RETURNS TABLE (
    proposition_id UUID,
    text           TEXT,
    embedding      vector,
    rrf_score      REAL,
    adjusted_score REAL,
    source_kind    TEXT,
    chunk_id       UUID,
    subject_id     UUID,
    predicate      TEXT,
    object_id      UUID,
    asserted_at    TIMESTAMPTZ
)
LANGUAGE SQL STABLE
AS $$
WITH

retrieved AS (
    SELECT
        ARRAY(
            SELECT (b.item_id, b.kind, b.rank, b.raw_score)::pgkg_candidate
            FROM pgkg_bm25_candidates(q_text, p_namespace, p_session_id, k_initial) b
        )
        ||
        ARRAY(
            SELECT (v.item_id, v.kind, v.rank, v.raw_score)::pgkg_candidate
            FROM pgkg_vector_candidates(q_embedding, p_namespace, p_session_id, k_initial) v
        ) AS candidates
),

-- Seeds for graph expansion are the fused lexical+vector candidates; their
-- fused scores set both the seed-entity ordering and the neighbour floor.
seeds AS (
    SELECT ARRAY(
        SELECT (f.item_id, 'fused'::TEXT, 0, f.fused_score)::pgkg_candidate
        FROM retrieved r, pgkg_fuse(r.candidates, rrf_k) f
    ) AS candidates
),

expanded AS (
    SELECT ARRAY(
        SELECT (g.item_id, g.kind, g.rank, g.raw_score)::pgkg_candidate
        FROM pgkg_graph_candidates(
            CASE WHEN expand_graph THEN s.candidates ELSE '{}'::pgkg_candidate[] END,
            p_namespace
        ) g
    ) AS candidates
    FROM seeds s
),

fused AS (
    SELECT f.*
    FROM retrieved r, expanded x, pgkg_fuse(r.candidates || x.candidates, rrf_k) f
),

profiled AS (
    SELECT ap.*
    FROM pgkg_apply_profile(
        ARRAY(
            SELECT (f.item_id, 'fused'::TEXT, 0, f.fused_score)::pgkg_candidate
            FROM fused f
        ),
        recency_half_life_days
    ) ap
)

SELECT
    fused.item_id,
    p.text,
    p.embedding::vector,
    fused.fused_score,
    profiled.adjusted_score,
    CASE
        WHEN fused.in_kw AND fused.in_vec THEN 'both'
        WHEN fused.in_kw                  THEN 'kw'
        WHEN fused.in_vec                 THEN 'vec'
        ELSE                                   'graph'
    END,
    p.chunk_id,
    p.subject_id,
    p.predicate,
    p.object_id,
    p.asserted_at
FROM fused
JOIN propositions p ON p.id = fused.item_id
JOIN profiled ON profiled.item_id = fused.item_id
ORDER BY profiled.adjusted_score DESC
LIMIT k_retrieve;
$$;
